services:
  db:
    image: mysql:5.7
    container_name: wordpress_docker_db
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_docker_app
    platform: linux/amd64
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wordpress:/var/www/html  # WordPressのすべてのファイルをマウント
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  # Tailwind CSSビルドサービス
  tailwind:
    image: node:18-alpine
    container_name: wordpress_tailwind_builder
    volumes:
      - ./wordpress/wp-content/themes/millecli:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    restart: always

volumes:
  db_data: {}

# 備考
## platform の指定は、MySQL イメージが linux/arm64/v8 に対応していないため
## M1/M2/M3 Mac は arm64 ベースのため
