# ===========================================
# Production Build Configuration
# ===========================================
# このファイルは本番環境用イメージのビルドとテストに使用します
# 実際のAWSデプロイでは、このイメージをECRにプッシュして使用します

version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}:${VERSION:-latest}
    container_name: wordpress_production_test
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wordpress_production_db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - db_data_prod:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wordpress_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data_prod:

networks:
  wordpress_network:
    driver: bridge
